apiVersion: v1
kind: Service
metadata:
  name: bookmarks-pwa-svc
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: bookmarks-pwa
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: bookmarks-pwa
    tier: frontend